name: Container

on:
  pull_request:
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: remotebrowser/shared-github-actions/container-health-check@v1
        with:
          image-name: headline-hub
          port-mapping: 3001:3001
          health-url: http://localhost:3001/health
          health-match: OK
