# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy headline-hub-gateway
    runs-on: ubuntu-22.04
    concurrency: deploy-headline-hub-gateway
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: remotebrowser/shared-github-actions/deploy-fly@v1
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: lambda_gateway
          doppler-config: lambda_gateway
          app-name: headline-hub-gateway
          fly-toml: fly.toml
